# development:
#   cloud_name: "dj1gc3zhg"
#   api_key: <%= Rails.application.credentials.cloudinary.api_key %>
#   api_secret: <%= Rails.application.credentials.cloudinary.secret %>

# production:
#   cloud_name: "dj1gc3zhg"
#   api_key: <%= Rails.application.credentials.cloudinary.api_key %>
#   api_secret: <%= Rails.application.credentials.cloudinary.secret %>
